name: Checks
on: push
jobs:
  check-manpage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Check manpage
    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt-get -y install libunwind-dev binutils-dev libiberty-dev help2man

      - name: Compile Austin
        run: |
          autoreconf --install
          ./configure
          make

      - name: Generate manpage
        run: bash doc/genman.sh

      - name: Check manpage
        run: git diff --exit-code src/austin.1

  cppcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Static code analysis
    steps:
      - uses: actions/checkout@v2

      - name: Install cppcheck
        run: sudo apt-get -y install cppcheck

      - name: Check soure code
        run: cppcheck -q -f --error-exitcode=1 src

  codespell:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Codespell
    steps:
      - uses: actions/checkout@v2

      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - name: Install codespell
        run: pip install codespell

      - name: Check source code spelling
        run: codespell src





