name: Tests
on: push
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: Tests on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      # ---- LINUX ----

      - name: Compile Austin on Linux
        run: |
          autoreconf --install
          ./configure
          make
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install test dependencies on Linux
        run: |
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          # sudo add-apt-repository -y ppa:duggan/bats
          sudo apt-get -y install valgrind python2.{3..7} python3.{3..9} # bats
          npm install bats
        if: "startsWith(matrix.os, 'ubuntu')"

      - name: Run tests on Linux
        run: sudo node_modules/.bin/bats test/test.bats
        if: "startsWith(matrix.os, 'ubuntu')"

      - name: Show test logs
        run: |
          test -f /tmp/austin_tests.log && cat /tmp/austin_tests.log || true
          test -f ./test-suite.log && cat ./test-suite.log || true
        if: always() && startsWith(matrix.os, 'ubuntu')

      # ---- MACOS ----

      - name: Compile Austin on macOS
        run: gcc -Wall -O3 -Os src/*.c -o src/austin -DDEBUG
        if: startsWith(matrix.os, 'macos')

      - name: Install test dependencies on macOS
        run: |
          brew install python || brew upgrade python
          brew install python@3.8 || true
          brew install python@3.9 || true
          brew install bats-core || true
          brew cask install anaconda || true
        if: startsWith(matrix.os, 'macos')

      - name: Run tests on macOS
        run: sudo bats test/macos/test.bats
        if: startsWith(matrix.os, 'macos')

      - name: Show test logs
        run: test -f /tmp/austin_tests.log && cat /tmp/austin_tests.log
        if: always() && startsWith(matrix.os, 'macos')

      # ---- WINDOWS ----

      - name: Compile Austin on Windows
        run: |
          gcc.exe -O3 -o src/austin.exe src/*.c -lpsapi -lntdll -Wall -Os -s -DDEBUG
          src\austin.exe --usage
        if: startsWith(matrix.os, 'windows')

      - name: Install test dependencies on Windows
        run: |
          git clone --depth=1 https://github.com/bats-core/bats-core.git
        if: "startsWith(matrix.os, 'windows')"

      - name: Run tests on Windows
        run: |
          bats-core/bin/bats test/win/test.bats
        if: startsWith(matrix.os, 'windows')
      
      - name: Show austin logs
        run: test -f /tmp/austin.log && cat /tmp/austin.log || true
        if: always() && startsWith(matrix.os, 'windows')
